# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 080c25c80f40c25903f4476444309d4aa2f9b93fe106ecc8f61611436abb0c514eb89b5085de4068a9c098c6bedbd0b62cf807b2f19a4c52cbbb56ee22c92a0d

test:
  secret_key_base: bed612ca8772ab8e99476519c4030f8f738a6016ad9ff5c3f5275cedcdc125ec967d50b076d75a5e25e8b18f8239b16303b4929e93a261118306bd1f1f3ea722

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
